import type { Chemical, Reaction } from './types';

export const CHEMICALS: Chemical[] = [
  // Core reactants and compounds for existing reactions
  { id: 'H2', name: 'Hydrogen Gas', formula: 'H₂', state: 'g', color: 'bg-blue-200', molarMass: 2.016, boilingPoint: -252.87 },
  { id: 'O2', name: 'Oxygen Gas', formula: 'O₂', state: 'g', color: 'bg-red-200', molarMass: 31.998, boilingPoint: -183 },
  { id: 'H2O', name: 'Water', formula: 'H₂O', state: 'l', color: 'bg-blue-400', molarMass: 18.015, meltingPoint: 0, boilingPoint: 100 },
  { 
    id: 'Na', 
    name: 'Sodium', 
    formula: 'Na', 
    state: 's', 
    color: 'bg-red-300', 
    atomicNumber: 11, 
    molarMass: 22.990, 
    meltingPoint: 97.8, 
    boilingPoint: 883,
    category: "alkali metal",
    group: 1,
    period: 3,
    block: "s",
    electronConfiguration: "[Ne] 3s¹",
    valenceElectrons: 1,
    electronegativityPauling: 0.93,
    atomicRadius: 180,
    ionizationEnergy: 495.8,
    electronAffinity: 52.8,
    densityGPerCm3: 0.968,
    crystalStructure: "body-centered cubic",
    commonOxidationStates: [1],
    reactivity: "highly reactive, especially with water",
    safety: {
      hazardClass: "water-reactive",
      ghsPictograms: ["GHS02", "GHS05"],
      handlingNote: "Reacts violently with water to produce flammable hydrogen gas. Handle with tongs, never with bare hands. Store under mineral oil.",
      storage: "Under inert liquid like mineral oil to prevent reaction with air/moisture."
    },
    uses: ["Sodium-vapor lamps (streetlights)", "Table salt (as NaCl)", "Industrial chemical synthesis", "Nuclear reactor coolant"],
    discovery: {
      year: 1807,
      discoverer: "Humphry Davy"
    }
  },
  { id: 'Cl2', name: 'Chlorine Gas', formula: 'Cl₂', state: 'g', color: 'bg-yellow-200', molarMass: 70.906, boilingPoint: -34.04 },
  { id: 'NaCl', name: 'Sodium Chloride', formula: 'NaCl', state: 's', color: 'bg-white', molarMass: 58.44, meltingPoint: 801, boilingPoint: 1413 },
  { id: 'HCl', name: 'Hydrochloric Acid', formula: 'HCl', state: 'aq', color: 'bg-green-200', molarMass: 36.46 },
  { id: 'NaOH', name: 'Sodium Hydroxide', formula: 'NaOH', state: 'aq', color: 'bg-purple-200', molarMass: 40.00 },
  { id: 'C', name: 'Carbon', formula: 'C', state: 's', color: 'bg-gray-800', atomicNumber: 6, molarMass: 12.011, meltingPoint: 3550 },
  { id: 'Fe', name: 'Iron', formula: 'Fe', state: 's', color: 'bg-orange-800', atomicNumber: 26, molarMass: 55.845, meltingPoint: 1538, boilingPoint: 2862 },

  // Additional compounds for more reactions
  { id: 'CH4', name: 'Methane', formula: 'CH₄', state: 'g', color: 'bg-gray-200', molarMass: 16.04, boilingPoint: -161.5 },
  { id: 'CO2', name: 'Carbon Dioxide', formula: 'CO₂', state: 'g', color: 'bg-gray-200', molarMass: 44.01, meltingPoint: -78.5 }, // Sublimation point
  { id: 'H2O2', name: 'Hydrogen Peroxide', formula: 'H₂O₂', state: 'aq', color: 'bg-cyan-200', molarMass: 34.014 },
  { id: 'MgCl2', name: 'Magnesium Chloride', formula: 'MgCl₂', state: 'aq', color: 'bg-green-300', molarMass: 95.211 },
  { id: 'ZnCl2', name: 'Zinc Chloride', formula: 'ZnCl₂', state: 'aq', color: 'bg-blue-200', molarMass: 136.315 },
  { id: 'AgNO3', name: 'Silver Nitrate', formula: 'AgNO₃', state: 'aq', color: 'bg-gray-300', molarMass: 169.87 },
  { id: 'AgCl', name: 'Silver Chloride', formula: 'AgCl', state: 's', color: 'bg-white', molarMass: 143.32, meltingPoint: 455, boilingPoint: 1550 },
  { id: 'NaNO3', name: 'Sodium Nitrate', formula: 'NaNO₃', state: 'aq', color: 'bg-gray-200', molarMass: 84.9947 },

  // Periodic Table Elements (excluding duplicates from above)
  { id: 'H', name: 'Hydrogen', formula: 'H', state: 'g', color: 'bg-pink-300', atomicNumber: 1, molarMass: 1.008 },
  { id: 'He', name: 'Helium', formula: 'He', state: 'g', color: 'bg-gray-200', atomicNumber: 2, molarMass: 4.0026 },
  { id: 'Li', name: 'Lithium', formula: 'Li', state: 's', color: 'bg-red-300', atomicNumber: 3, molarMass: 6.94 },
  { id: 'Be', name: 'Beryllium', formula: 'Be', state: 's', color: 'bg-orange-300', atomicNumber: 4, molarMass: 9.0122 },
  { id: 'B', name: 'Boron', formula: 'B', state: 's', color: 'bg-indigo-300', atomicNumber: 5, molarMass: 10.81 },
  { id: 'N', name: 'Nitrogen', formula: 'N', state: 'g', color: 'bg-pink-300', atomicNumber: 7, molarMass: 14.007 },
  { 
    id: 'O', 
    name: 'Oxygen', 
    formula: 'O', 
    state: 'g', 
    color: 'bg-pink-300', 
    atomicNumber: 8, 
    molarMass: 15.999,
    category: "nonmetal",
    group: 16,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁴",
    valenceElectrons: 6,
    electronegativityPauling: 3.44,
    atomicRadius: 60,
    ionizationEnergy: 1313.9,
    electronAffinity: 141.0,
    meltingPoint: -218.8,
    boilingPoint: -183.0,
    densityGPerCm3: 0.001429,
    crystalStructure: null,
    commonOxidationStates: [-2, -1],
    reactivity: "highly reactive",
    conductivity: {
      thermal: 0.0267,
      electrical: 1e-15
    },
    safety: {
      hazardClass: "oxidizer",
      ghsPictograms: ["GHS03"],
      handlingNote: "Supports combustion. Keep away from flammable materials.",
      storage: "In gas cylinders, secured upright."
    },
    uses: ["Respiration", "Steelmaking", "Rocket propellant oxidizer"],
    discovery: {
      year: 1774,
      discoverer: "Joseph Priestley"
    }
  },
  { id: 'F', name: 'Fluorine', formula: 'F', state: 'g', color: 'bg-teal-300', atomicNumber: 9, molarMass: 18.998 },
  { id: 'Ne', name: 'Neon', formula: 'Ne', state: 'g', color: 'bg-gray-200', atomicNumber: 10, molarMass: 20.180 },
  { id: 'Mg', name: 'Magnesium', formula: 'Mg', state: 's', color: 'bg-orange-300', atomicNumber: 12, molarMass: 24.305, meltingPoint: 650 },
  { id: 'Al', name: 'Aluminum', formula: 'Al', state: 's', color: 'bg-green-300', atomicNumber: 13, molarMass: 26.982 },
  { id: 'Si', name: 'Silicon', formula: 'Si', state: 's', color: 'bg-indigo-300', atomicNumber: 14, molarMass: 28.085 },
  { id: 'P', name: 'Phosphorus', formula: 'P', state: 's', color: 'bg-pink-300', atomicNumber: 15, molarMass: 30.974 },
  { id: 'S', name: 'Sulfur', formula: 'S', state: 's', color: 'bg-yellow-400', atomicNumber: 16, molarMass: 32.06 },
  { id: 'Cl', name: 'Chlorine', formula: 'Cl', state: 'g', color: 'bg-teal-300', atomicNumber: 17, molarMass: 35.45 },
  { id: 'Ar', name: 'Argon', formula: 'Ar', state: 'g', color: 'bg-gray-200', atomicNumber: 18, molarMass: 39.948 },
  { id: 'K', name: 'Potassium', formula: 'K', state: 's', color: 'bg-red-300', atomicNumber: 19, molarMass: 39.098 },
  { id: 'Ca', name: 'Calcium', formula: 'Ca', state: 's', color: 'bg-orange-300', atomicNumber: 20, molarMass: 40.078 },
  { id: 'Sc', name: 'Scandium', formula: 'Sc', state: 's', color: 'bg-blue-300', atomicNumber: 21, molarMass: 44.956, meltingPoint: 1541, boilingPoint: 2836 },
  { id: 'Ti', name: 'Titanium', formula: 'Ti', state: 's', color: 'bg-blue-300', atomicNumber: 22, molarMass: 47.867, meltingPoint: 1668, boilingPoint: 3287 },
  { id: 'V', name: 'Vanadium', formula: 'V', state: 's', color: 'bg-blue-300', atomicNumber: 23, molarMass: 50.942, meltingPoint: 1910, boilingPoint: 3407 },
  { id: 'Cr', name: 'Chromium', formula: 'Cr', state: 's', color: 'bg-blue-300', atomicNumber: 24, molarMass: 51.996, meltingPoint: 1907, boilingPoint: 2671 },
  { id: 'Mn', name: 'Manganese', formula: 'Mn', state: 's', color: 'bg-blue-300', atomicNumber: 25, molarMass: 54.938, meltingPoint: 1246, boilingPoint: 2061 },
  { id: 'Co', name: 'Cobalt', formula: 'Co', state: 's', color: 'bg-blue-300', atomicNumber: 27, molarMass: 58.933, meltingPoint: 1495, boilingPoint: 2927 },
  { id: 'Ni', name: 'Nickel', formula: 'Ni', state: 's', color: 'bg-blue-300', atomicNumber: 28, molarMass: 58.693, meltingPoint: 1455, boilingPoint: 2913 },
  { id: 'Cu', name: 'Copper', formula: 'Cu', state: 's', color: 'bg-orange-500', atomicNumber: 29, molarMass: 63.546, meltingPoint: 1084.62, boilingPoint: 2562 },
  { id: 'Zn', name: 'Zinc', formula: 'Zn', state: 's', color: 'bg-blue-300', atomicNumber: 30, molarMass: 65.38, meltingPoint: 419.5 },
  { id: 'Ga', name: 'Gallium', formula: 'Ga', state: 's', color: 'bg-green-300', atomicNumber: 31, molarMass: 69.723 },
  { id: 'Ge', name: 'Germanium', formula: 'Ge', state: 's', color: 'bg-indigo-300', atomicNumber: 32, molarMass: 72.630 },
  { id: 'As', name: 'Arsenic', formula: 'As', state: 's', color: 'bg-indigo-300', atomicNumber: 33, molarMass: 74.922 },
  { id: 'Se', name: 'Selenium', formula: 'Se', state: 's', color: 'bg-pink-300', atomicNumber: 34, molarMass: 78.971 },
  { id: 'Br', name: 'Bromine', formula: 'Br', state: 'l', color: 'bg-teal-400', atomicNumber: 35, molarMass: 79.904, meltingPoint: -7.2, boilingPoint: 58.8 },
  { id: 'Kr', name: 'Krypton', formula: 'Kr', state: 'g', color: 'bg-gray-200', atomicNumber: 36, molarMass: 83.798 },
  { id: 'Rb', name: 'Rubidium', formula: 'Rb', state: 's', color: 'bg-red-300', atomicNumber: 37, molarMass: 85.468 },
  { id: 'Sr', name: 'Strontium', formula: 'Sr', state: 's', color: 'bg-orange-300', atomicNumber: 38, molarMass: 87.62 },
  { id: 'Y', name: 'Yttrium', formula: 'Y', state: 's', color: 'bg-blue-300', atomicNumber: 39, molarMass: 88.906, meltingPoint: 1526, boilingPoint: 3336 },
  { id: 'Zr', name: 'Zirconium', formula: 'Zr', state: 's', color: 'bg-blue-300', atomicNumber: 40, molarMass: 91.224, meltingPoint: 1855, boilingPoint: 4409 },
  { id: 'Nb', name: 'Niobium', formula: 'Nb', state: 's', color: 'bg-blue-300', atomicNumber: 41, molarMass: 92.906, meltingPoint: 2477, boilingPoint: 4744 },
  { id: 'Mo', name: 'Molybdenum', formula: 'Mo', state: 's', color: 'bg-blue-300', atomicNumber: 42, molarMass: 95.96, meltingPoint: 2623, boilingPoint: 4639 },
  { id: 'Tc', name: 'Technetium', formula: 'Tc', state: 's', color: 'bg-blue-300', atomicNumber: 43, molarMass: 98 },
  { id: 'Ru', name: 'Ruthenium', formula: 'Ru', state: 's', color: 'bg-blue-300', atomicNumber: 44, molarMass: 101.07 },
  { id: 'Rh', name: 'Rhodium', formula: 'Rh', state: 's', color: 'bg-blue-300', atomicNumber: 45, molarMass: 102.91 },
  { id: 'Pd', name: 'Palladium', formula: 'Pd', state: 's', color: 'bg-blue-300', atomicNumber: 46, molarMass: 106.42, meltingPoint: 1554.9, boilingPoint: 2963 },
  { id: 'Ag', name: 'Silver', formula: 'Ag', state: 's', color: 'bg-gray-400', atomicNumber: 47, molarMass: 107.87, meltingPoint: 961.78, boilingPoint: 2162 },
  { id: 'Cd', name: 'Cadmium', formula: 'Cd', state: 's', color: 'bg-blue-300', atomicNumber: 48, molarMass: 112.41 },
  { id: 'In', name: 'Indium', formula: 'In', state: 's', color: 'bg-green-300', atomicNumber: 49, molarMass: 114.82 },
  { id: 'Sn', name: 'Tin', formula: 'Sn', state: 's', color: 'bg-green-300', atomicNumber: 50, molarMass: 118.71 },
  { id: 'Sb', name: 'Antimony', formula: 'Sb', state: 's', color: 'bg-indigo-300', atomicNumber: 51, molarMass: 121.76 },
  { id: 'Te', name: 'Tellurium', formula: 'Te', state: 's', color: 'bg-indigo-300', atomicNumber: 52, molarMass: 127.60 },
  { id: 'I', name: 'Iodine', formula: 'I', state: 's', color: 'bg-teal-500', atomicNumber: 53, molarMass: 126.90 },
  { id: 'Xe', name: 'Xenon', formula: 'Xe', state: 'g', color: 'bg-gray-200', atomicNumber: 54, molarMass: 131.29 },
  { id: 'Cs', name: 'Cesium', formula: 'Cs', state: 's', color: 'bg-red-300', atomicNumber: 55, molarMass: 132.91 },
  { id: 'Ba', name: 'Barium', formula: 'Ba', state: 's', color: 'bg-orange-300', atomicNumber: 56, molarMass: 137.33 },
  { id: 'La', name: 'Lanthanum', formula: 'La', state: 's', color: 'bg-yellow-300', atomicNumber: 57, molarMass: 138.91 },
  { id: 'Ce', name: 'Cerium', formula: 'Ce', state: 's', color: 'bg-yellow-300', atomicNumber: 58, molarMass: 140.12 },
  { id: 'Pr', name: 'Praseodymium', formula: 'Pr', state: 's', color: 'bg-yellow-300', atomicNumber: 59, molarMass: 140.91 },
  { id: 'Nd', name: 'Neodymium', formula: 'Nd', state: 's', color: 'bg-yellow-300', atomicNumber: 60, molarMass: 144.24 },
  { id: 'Pm', name: 'Promethium', formula: 'Pm', state: 's', color: 'bg-yellow-300', atomicNumber: 61, molarMass: 145 },
  { id: 'Sm', name: 'Samarium', formula: 'Sm', state: 's', color: 'bg-yellow-300', atomicNumber: 62, molarMass: 150.36 },
  { id: 'Eu', name: 'Europium', formula: 'Eu', state: 's', color: 'bg-yellow-300', atomicNumber: 63, molarMass: 151.96 },
  { id: 'Gd', name: 'Gadolinium', formula: 'Gd', state: 's', color: 'bg-yellow-300', atomicNumber: 64, molarMass: 157.25 },
  { id: 'Tb', name: 'Terbium', formula: 'Tb', state: 's', color: 'bg-yellow-300', atomicNumber: 65, molarMass: 158.93 },
  { id: 'Dy', name: 'Dysprosium', formula: 'Dy', state: 's', color: 'bg-yellow-300', atomicNumber: 66, molarMass: 162.50 },
  { id: 'Ho', name: 'Holmium', formula: 'Ho', state: 's', color: 'bg-yellow-300', atomicNumber: 67, molarMass: 164.93 },
  { id: 'Er', name: 'Erbium', formula: 'Er', state: 's', color: 'bg-yellow-300', atomicNumber: 68, molarMass: 167.26 },
  { id: 'Tm', name: 'Thulium', formula: 'Tm', state: 's', color: 'bg-yellow-300', atomicNumber: 69, molarMass: 168.93 },
  { id: 'Yb', name: 'Ytterbium', formula: 'Yb', state: 's', color: 'bg-yellow-300', atomicNumber: 70, molarMass: 173.05 },
  { id: 'Lu', name: 'Lutetium', formula: 'Lu', state: 's', color: 'bg-yellow-300', atomicNumber: 71, molarMass: 174.97 },
  { id: 'Hf', name: 'Hafnium', formula: 'Hf', state: 's', color: 'bg-blue-300', atomicNumber: 72, molarMass: 178.49 },
  { id: 'Ta', name: 'Tantalum', formula: 'Ta', state: 's', color: 'bg-blue-300', atomicNumber: 73, molarMass: 180.95 },
  { id: 'W', name: 'Tungsten', formula: 'W', state: 's', color: 'bg-blue-300', atomicNumber: 74, molarMass: 183.84 },
  { id: 'Re', name: 'Rhenium', formula: 'Re', state: 's', color: 'bg-blue-300', atomicNumber: 75, molarMass: 186.21 },
  { id: 'Os', name: 'Osmium', formula: 'Os', state: 's', color: 'bg-blue-300', atomicNumber: 76, molarMass: 190.23 },
  { id: 'Ir', name: 'Iridium', formula: 'Ir', state: 's', color: 'bg-blue-300', atomicNumber: 77, molarMass: 192.22 },
  { id: 'Pt', name: 'Platinum', formula: 'Pt', state: 's', color: 'bg-blue-300', atomicNumber: 78, molarMass: 195.08, meltingPoint: 1768.3, boilingPoint: 3825 },
  { id: 'Au', name: 'Gold', formula: 'Au', state: 's', color: 'bg-yellow-500', atomicNumber: 79, molarMass: 196.97, meltingPoint: 1064.18, boilingPoint: 2856 },
  { id: 'Hg', name: 'Mercury', formula: 'Hg', state: 'l', color: 'bg-gray-500', atomicNumber: 80, molarMass: 200.59, meltingPoint: -38.83, boilingPoint: 356.7 },
  { id: 'Tl', name: 'Thallium', formula: 'Tl', state: 's', color: 'bg-green-300', atomicNumber: 81, molarMass: 204.38 },
  { id: 'Pb', name: 'Lead', formula: 'Pb', state: 's', color: 'bg-green-300', atomicNumber: 82, molarMass: 207.2 },
  { id: 'Bi', name: 'Bismuth', formula: 'Bi', state: 's', color: 'bg-green-300', atomicNumber: 83, molarMass: 208.98 },
  { id: 'Po', name: 'Polonium', formula: 'Po', state: 's', color: 'bg-indigo-300', atomicNumber: 84, molarMass: 209 },
  { id: 'At', name: 'Astatine', formula: 'At', state: 's', color: 'bg-teal-600', atomicNumber: 85, molarMass: 210 },
  { id: 'Rn', name: 'Radon', formula: 'Rn', state: 'g', color: 'bg-gray-200', atomicNumber: 86, molarMass: 222 },
  { id: 'Fr', name: 'Francium', formula: 'Fr', state: 's', color: 'bg-red-300', atomicNumber: 87, molarMass: 223 },
  { id: 'Ra', name: 'Radium', formula: 'Ra', state: 's', color: 'bg-orange-300', atomicNumber: 88, molarMass: 226 },
  { id: 'Ac', name: 'Actinium', formula: 'Ac', state: 's', color: 'bg-purple-300', atomicNumber: 89, molarMass: 227 },
  { id: 'Th', name: 'Thorium', formula: 'Th', state: 's', color: 'bg-purple-300', atomicNumber: 90, molarMass: 232.04 },
  { id: 'Pa', name: 'Protactinium', formula: 'Pa', state: 's', color: 'bg-purple-300', atomicNumber: 91, molarMass: 231.04 },
  { id: 'U', name: 'Uranium', formula: 'U', state: 's', color: 'bg-purple-300', atomicNumber: 92, molarMass: 238.03 },
  { id: 'Np', name: 'Neptunium', formula: 'Np', state: 's', color: 'bg-purple-300', atomicNumber: 93, molarMass: 237 },
  { id: 'Pu', name: 'Plutonium', formula: 'Pu', state: 's', color: 'bg-purple-300', atomicNumber: 94, molarMass: 244 },
  { id: 'Am', name: 'Americium', formula: 'Am', state: 's', color: 'bg-purple-300', atomicNumber: 95, molarMass: 243 },
  { id: 'Cm', name: 'Curium', formula: 'Cm', state: 's', color: 'bg-purple-300', atomicNumber: 96, molarMass: 247 },
  { id: 'Bk', name: 'Berkelium', formula: 'Bk', state: 's', color: 'bg-purple-300', atomicNumber: 97, molarMass: 247 },
  { id: 'Cf', name: 'Californium', formula: 'Cf', state: 's', color: 'bg-purple-300', atomicNumber: 98, molarMass: 251 },
  { id: 'Es', name: 'Einsteinium', formula: 'Es', state: 's', color: 'bg-purple-300', atomicNumber: 99, molarMass: 252 },
  { id: 'Fm', name: 'Fermium', formula: 'Fm', state: 's', color: 'bg-purple-300', atomicNumber: 100, molarMass: 257 },
  { id: 'Md', name: 'Mendelevium', formula: 'Md', state: 's', color: 'bg-purple-300', atomicNumber: 101, molarMass: 258 },
  { id: 'No', name: 'Nobelium', formula: 'No', state: 's', color: 'bg-purple-300', atomicNumber: 102, molarMass: 259 },
  { id: 'Lr', name: 'Lawrencium', formula: 'Lr', state: 's', color: 'bg-purple-300', atomicNumber: 103, molarMass: 262 },
  { id: 'Rf', name: 'Rutherfordium', formula: 'Rf', state: 's', color: 'bg-blue-300', atomicNumber: 104, molarMass: 267 },
  { id: 'Db', name: 'Dubnium', formula: 'Db', state: 's', color: 'bg-blue-300', atomicNumber: 105, molarMass: 268 },
  { id: 'Sg', name: 'Seaborgium', formula: 'Sg', state: 's', color: 'bg-blue-300', atomicNumber: 106, molarMass: 271 },
  { id: 'Bh', name: 'Bohrium', formula: 'Bh', state: 's', color: 'bg-blue-300', atomicNumber: 107, molarMass: 270 },
  { id: 'Hs', name: 'Hassium', formula: 'Hs', state: 's', color: 'bg-blue-300', atomicNumber: 108, molarMass: 277 },
  { id: 'Mt', name: 'Meitnerium', formula: 'Mt', state: 's', color: 'bg-blue-300', atomicNumber: 109, molarMass: 276 },
  { id: 'Ds', name: 'Darmstadtium', formula: 'Ds', state: 's', color: 'bg-blue-300', atomicNumber: 110, molarMass: 281 },
  { id: 'Rg', name: 'Roentgenium', formula: 'Rg', state: 's', color: 'bg-blue-300', atomicNumber: 111, molarMass: 280 },
  { id: 'Cn', name: 'Copernicium', formula: 'Cn', state: 'l', color: 'bg-blue-300', atomicNumber: 112, molarMass: 285 },
  { id: 'Nh', name: 'Nihonium', formula: 'Nh', state: 's', color: 'bg-green-300', atomicNumber: 113, molarMass: 284 },
  { id: 'Fl', name: 'Flerovium', formula: 'Fl', state: 's', color: 'bg-green-300', atomicNumber: 114, molarMass: 289 },
  { id: 'Mc', name: 'Moscovium', formula: 'Mc', state: 's', color: 'bg-green-300', atomicNumber: 115, molarMass: 288 },
  { id: 'Lv', name: 'Livermorium', formula: 'Lv', state: 's', color: 'bg-green-300', atomicNumber: 116, molarMass: 293 },
  { id: 'Ts', name: 'Tennessine', formula: 'Ts', state: 's', color: 'bg-teal-600', atomicNumber: 117, molarMass: 294 },
  { id: 'Og', name: 'Oganesson', formula: 'Og', state: 'g', color: 'bg-gray-200', atomicNumber: 118, molarMass: 294 },
];

export const REACTIONS: Reaction[] = [
  {
    id: 'H2O_formation',
    name: 'Water Formation',
    reactants: [{ chemicalId: 'H2', coefficient: 2 }, { chemicalId: 'O2', coefficient: 1 }],
    products: [{ chemicalId: 'H2O', coefficient: 2 }],
    equation: '2H₂ (g) + O₂ (g) → 2H₂O (l)',
    description: 'The formation of water from hydrogen and oxygen is a highly exothermic reaction, famously used in rocket engines.',
    warning: 'Explosive reaction! Requires an ignition source.',
    kinetics: { baseDuration: 500, tempFactor: 1.05 },
  },
  {
    id: 'NaCl_formation',
    name: 'Salt Formation',
    reactants: [{ chemicalId: 'Na', coefficient: 2 }, { chemicalId: 'Cl2', coefficient: 1 }],
    products: [{ chemicalId: 'NaCl', coefficient: 2 }],
    equation: '2Na (s) + Cl₂ (g) → 2NaCl (s)',
    description: 'Sodium, a highly reactive metal, reacts vigorously with chlorine gas to produce sodium chloride, or table salt.',
    warning: 'Violent reaction with bright yellow flame.',
    kinetics: { baseDuration: 1000, tempFactor: 1.1 },
  },
  {
    id: 'neutralization',
    name: 'Acid-Base Neutralization',
    reactants: [{ chemicalId: 'HCl', coefficient: 1 }, { chemicalId: 'NaOH', coefficient: 1 }],
    products: [{ chemicalId: 'NaCl', coefficient: 1 }, { chemicalId: 'H2O', coefficient: 1 }],
    equation: 'HCl (aq) + NaOH (aq) → NaCl (aq) + H₂O (l)',
    description: 'An acid-base neutralization reaction between hydrochloric acid and sodium hydroxide, producing salt and water.',
    kinetics: { baseDuration: 1500, tempFactor: 1.0 },
  },
  {
    id: 'CH4_combustion',
    name: 'Methane Combustion',
    reactants: [{ chemicalId: 'CH4', coefficient: 1 }, { chemicalId: 'O2', coefficient: 2 }],
    products: [{ chemicalId: 'CO2', coefficient: 1 }, { chemicalId: 'H2O', coefficient: 2 }],
    equation: 'CH₄ (g) + 2O₂ (g) → CO₂ (g) + 2H₂O (g)',
    description: 'The combustion of methane, a primary component of natural gas, releases energy in the form of heat and light.',
    warning: 'Exothermic reaction. Produces a flame.',
    kinetics: { baseDuration: 2000, tempFactor: 1.2 },
  },
  {
    id: 'C_combustion',
    name: 'Carbon Combustion',
    reactants: [{ chemicalId: 'C', coefficient: 1 }, { chemicalId: 'O2', coefficient: 1 }],
    products: [{ chemicalId: 'CO2', coefficient: 1 }],
    equation: 'C (s) + O₂ (g) → CO₂ (g)',
    description: 'Carbon, in the form of charcoal or coal, burns in the presence of oxygen to form carbon dioxide.',
    kinetics: { baseDuration: 5000, tempFactor: 1.5 },
  },
  {
    id: 'Mg_HCl_reaction',
    name: 'Magnesium and Acid',
    reactants: [{ chemicalId: 'Mg', coefficient: 1 }, { chemicalId: 'HCl', coefficient: 2 }],
    products: [{ chemicalId: 'MgCl2', coefficient: 1 }, { chemicalId: 'H2', coefficient: 1 }],
    equation: 'Mg (s) + 2HCl (aq) → MgCl₂ (aq) + H₂ (g)',
    description: 'Magnesium metal reacts rapidly with hydrochloric acid, producing hydrogen gas bubbles and magnesium chloride.',
    kinetics: { baseDuration: 3000, tempFactor: 1.3 },
  },
  {
    id: 'Zn_HCl_reaction',
    name: 'Zinc and Acid',
    reactants: [{ chemicalId: 'Zn', coefficient: 1 }, { chemicalId: 'HCl', coefficient: 2 }],
    products: [{ chemicalId: 'ZnCl2', coefficient: 1 }, { chemicalId: 'H2', coefficient: 1 }],
    equation: 'Zn (s) + 2HCl (aq) → ZnCl₂ (aq) + H₂ (g)',
    description: 'Zinc metal reacts with hydrochloric acid in a single displacement reaction to produce hydrogen gas and zinc chloride.',
    kinetics: { baseDuration: 8000, tempFactor: 1.4 },
  },
  {
    id: 'AgCl_precipitation',
    name: 'Precipitation Reaction',
    reactants: [{ chemicalId: 'AgNO3', coefficient: 1 }, { chemicalId: 'NaCl', coefficient: 1 }],
    products: [{ chemicalId: 'AgCl', coefficient: 1 }, { chemicalId: 'NaNO3', coefficient: 1 }],
    equation: 'AgNO₃ (aq) + NaCl (aq) → AgCl (s) ↓ + NaNO₃ (aq)',
    description: 'When solutions of silver nitrate and sodium chloride are mixed, a white precipitate of silver chloride is formed.',
    kinetics: { baseDuration: 1000, tempFactor: 1.0 },
  },
  {
    id: 'H2O2_decomposition',
    name: 'Hydrogen Peroxide Decomposition',
    reactants: [{ chemicalId: 'H2O2', coefficient: 2 }],
    products: [{ chemicalId: 'H2O', coefficient: 2 }, { chemicalId: 'O2', coefficient: 1 }],
    equation: '2H₂O₂ (aq) → 2H₂O (l) + O₂ (g)',
    description: 'Hydrogen peroxide decomposes into water and oxygen gas. This reaction is often accelerated by a catalyst.',
    kinetics: { baseDuration: 10000, tempFactor: 1.2 },
  }
];